apiVersion: v1
kind: Service
metadata:
  name: go
  labels:
    app: go
spec:
  ports:
    - port: 8081
  selector:
    app: go
    tier: frontend
  #type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  selector:
    matchLabels:
      app: go
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go
        tier: frontend
    spec:
      containers:
      - image: dana2cr/go:v1
        name: go
        ports:
        - containerPort: 8081
          name: go
